<?php
	function getCss(){
		$css=array(
			'btn'=>"text-decoration: none;display: inline-block;padding: 4px 10px 4px;margin-bottom: 0;font-size: 13px;line-height: 18px;color: #333333;text-align: center;text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);vertical-align: middle;background-color: #f5f5f5;background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6);background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6);background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6));background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6);background-image: -o-linear-gradient(top, #ffffff, #e6e6e6);background-image: linear-gradient(top, #ffffff, #e6e6e6);background-repeat: repeat-x;filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#e6e6e6', GradientType=0);border-color: #e6e6e6 #e6e6e6 #bfbfbf;border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);border: 1px solid #ccc;border-bottom-color: #bbb;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;-webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);-moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);cursor: pointer;",
			'btn-primary'=>"text-decoration: none;display: inline-block;padding: 4px 10px 4px;margin-bottom: 0;font-size: 13px;line-height: 18px;color: #333333;text-align: center;text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);vertical-align: middle;background-color: #f5f5f5;background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6);background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6);background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6));background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6);background-image: -o-linear-gradient(top, #ffffff, #e6e6e6);background-image: linear-gradient(top, #ffffff, #e6e6e6);background-repeat: repeat-x;filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#e6e6e6', GradientType=0);border-color: #e6e6e6 #e6e6e6 #bfbfbf;border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);border: 1px solid #ccc;border-bottom-color: #bbb;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;-webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);-moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);cursor: pointer;text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);color: #ffffff; background-color: #006dcc;background-image: -moz-linear-gradient(top, #0088cc, #0044cc);background-image: -ms-linear-gradient(top, #0088cc, #0044cc);background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#0088cc), to(#0044cc));background-image: -webkit-linear-gradient(top, #0088cc, #0044cc);background-image: -o-linear-gradient(top, #0088cc, #0044cc);background-image: linear-gradient(top, #0088cc, #0044cc);background-repeat: repeat-x;filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#0088cc', endColorstr='#0044cc', GradientType=0);border-color: #0044cc #0044cc #002a80;border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);",
			's-corner-all'=>"-moz-border-radius-topleft: 7px !important; -webkit-border-top-left-radius: 7px !important; -khtml-border-top-left-radius: 7px !important; border-top-left-radius: 7px !important;-moz-border-radius-topright: 7px !important; -webkit-border-top-right-radius: 7px !important; -khtml-border-top-right-radius: 7px !important; border-top-right-radius: 7px !important;-moz-border-radius-bottomleft: 7px !important; -webkit-border-bottom-left-radius: 7px !important; -khtml-border-bottom-left-radius: 7px !important; border-bottom-left-radius: 7px !important;-moz-border-radius-bottomright: 7px !important; -webkit-border-bottom-right-radius: 7px !important; -khtml-border-bottom-right-radius: 7px !important; border-bottom-right-radius: 7px !important;",
			'l-corner-all'=>"-moz-border-radius-topleft: 15px !important; -webkit-border-top-left-radius: 15px !important; -khtml-border-top-left-radius: 15px !important; border-top-left-radius: 15px !important;-moz-border-radius-topright: 15px !important; -webkit-border-top-right-radius: 15px !important; -khtml-border-top-right-radius: 15px !important; border-top-right-radius: 15px !important;-moz-border-radius-bottomleft: 15px !important; -webkit-border-bottom-left-radius: 15px !important; -khtml-border-bottom-left-radius: 15px !important; border-bottom-left-radius: 15px !important;-moz-border-radius-bottomright: 15px !important; -webkit-border-bottom-right-radius: 15px !important; -khtml-border-bottom-right-radius: 15px !important; border-bottom-right-radius: 15px !important;",
			'm-corner-all'=>"-moz-border-radius-topleft: 11px !important; -webkit-border-top-left-radius: 11px !important; -khtml-border-top-left-radius: 11px !important; border-top-left-radius: 11px !important;-moz-border-radius-topright: 11px !important; -webkit-border-top-right-radius: 11px !important; -khtml-border-top-right-radius: 11px !important; border-top-right-radius: 11px !important;-moz-border-radius-bottomleft: 11px !important; -webkit-border-bottom-left-radius: 11px !important; -khtml-border-bottom-left-radius: 11px !important; border-bottom-left-radius: 11px !important;-moz-border-radius-bottomright: 11px !important; -webkit-border-bottom-right-radius: 11px !important; -khtml-border-bottom-right-radius: 11px !important; border-bottom-right-radius: 11px !important;",
			'l-corner-top'=>"-moz-border-radius-topleft: 15px !important; -webkit-border-top-left-radius: 15px !important; -khtml-border-top-left-radius: 15px !important; border-top-left-radius: 15px !important;-moz-border-radius-topright: 15px !important; -webkit-border-top-right-radius: 15px !important; -khtml-border-top-right-radius: 15px !important; border-top-right-radius: 15px !important;",
			'l-corner-bottom'=>"-moz-border-radius-bottomleft: 15px !important; -webkit-border-bottom-left-radius: 15px !important; -khtml-border-bottom-left-radius: 15px !important; border-bottom-left-radius: 15px !important;-moz-border-radius-bottomright: 15px !important; -webkit-border-bottom-right-radius: 15px !important; -khtml-border-bottom-right-radius: 15px !important; border-bottom-right-radius: 15px !important;",
			'bluebtn'=>'background:#243E7D;padding:5px 10px;margin:15px 0px;display:inline-block;color:white;text-align:center;',
			'pinkbtn'=>'background:#f09;padding:5px 10px;margin:15px 0px;display:inline-block;color:white;text-align:center;',
			'bluecolor'=>"color:#243E7D;",
			'highlightcolor'=>"color:#0193be;",
			'pinkcolor'=>"color:#f09;",
			"a"=>"text-decoration: none;",
			"bold"=>"font-weight: bold;"
		);
		//$css['font_url']=FONT_URL;
		$css['font_name']='Arial';
		return $css;
	}
?>